In [1]:
import pandas as pd
pd.read_csv("example.csv")

,Div,Date,HomeTeam,AwayTeam,Full time home goals,Full time away goals,Full time result,Half time home goals,Half time away goals,Half time result,...,Betbrain max >2.5,Betbrain average >2.5,Betbrain max <2.5,Betbrain average <2.5,Betbrain Asian bookies,Betbrain Asian home handicap,Betbrain max Asian home odds,Betbrain average Asian home odds,Betbrain max Asian away odds,Betbrain average Asian away odds
0,E0,13/08/05,Aston Villa,Bolton,2,2,D,2,2,D,...,2.20,2.01,1.87,1.70,22,-0.25,2.10,2.01,1.92,1.84
1,E0,13/08/05,Everton,Man United,0,2,A,0,1,A,...,2.10,1.93,1.87,1.79,23,0.75,2.05,2.00,1.93,1.86
2,E0,13/08/05,Fulham,Birmingham,0,0,D,0,0,D,...,2.24,2.04,1.77,1.69,21,0.00,1.85,1.81,2.11,2.05
3,E0,13/08/05,Man City,West Brom,0,0,D,0,0,D,...,2.10,1.94,1.90,1.77,23,-0.75,2.19,2.10,1.83,1.76
4,E0,13/08/05,Middlesboro,Liverpool,0,0,D,0,0,D,...,2.23,2.02,1.80,1.71,21,0.25,1.89,1.86,2.04,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,07/05/06,Fulham,Middlesboro,1,0,H,0,0,D,...,2.15,2.00,1.80,1.74,20,-0.75,1.88,1.81,2.10,2.05
376,E0,07/05/06,Man United,Charlton,4,0,H,3,0,H,...,1.75,1.67,2.20,2.08,20,-1.75,1.93,1.90,2.04,1.96
377,E0,07/05/06,Newcastle,Chelsea,1,0,H,0,0,D,...,2.25,2.08,1.70,1.67,20,0.00,2.15,2.09,1.83,1.76
378,E0,07/05/06,Portsmouth,Liverpool,1,3,A,0,0,D,...,2.13,1.96,1.85,1.76,20,0.75,2.19,2.12,1.83,1.76
379,E0,07/05/06,West Ham,Tottenham,2,1,H,1,1,D,...,2.20,2.04,1.80,1.71,19,0.75,2.00,1.91,2.00,1.96

In [2]:
pd.read_csv("E0.csv")

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,...,1.76,0.50,2.09,1.84,2.04,1.88,2.09,1.88,2.03,1.85
1,E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,...,2.73,1.75,1.90,2.03,1.91,2.02,2.01,2.06,1.89,1.99
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,...,1.76,0.50,1.93,2.00,1.93,2.00,1.94,2.04,1.88,2.00
3,E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,...,1.87,-0.25,2.08,1.85,2.10,1.84,2.14,1.87,2.08,1.81
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,...,1.89,-1.00,1.97,1.96,1.99,1.93,2.19,1.97,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,E0,04/03/2023,15:00,Wolves,Tottenham,1,0,H,0,0,...,1.67,0.25,1.90,2.03,1.90,2.02,1.91,2.08,1.87,1.99
247,E0,04/03/2023,17:30,Southampton,Leicester,1,0,H,1,0,...,1.85,0.00,2.09,1.84,2.12,1.83,2.12,2.06,1.99,1.90
248,E0,05/03/2023,14:00,Nott'm Forest,Everton,2,2,D,1,2,...,1.51,0.00,2.11,1.79,2.13,1.82,2.17,1.85,2.09,1.80
249,E0,05/03/2023,16:30,Liverpool,Man United,7,0,H,1,0,...,2.16,0.00,1.75,2.05,1.77,2.17,1.92,2.20,1.79,2.10
250,E0,06/03/2023,20:00,Brentford,Fulham,3,2,H,1,1,...,1.84,-0.50,2.07,1.86,2.08,1.86,2.08,1.89,2.05,1.84